functionsDirectory = "/Users/tyler/neonburro/netlify/functions"
functionsDirectoryOrigin = "config-v1"
plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/tyler/neonburro/yarn dev"
publishOrigin = "config"
commandOrigin = "config"
command = "netlify deploy --prod"
functions = "/Users/tyler/neonburro/netlify/functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]